name: terrafetch
description: Add flair to your infrastructure repositories with Terrafetch.
author: RoseSecurity

branding:
  icon: cloud
  color: purple

inputs:
  github_token:
    description: GITHUB_TOKEN used for committing README updates
    default: ${{ github.token }}
    required: true
  output_file:
    description: README-style file that contains <!-- TERRAFETCH:START / END --> markers
    default: README.md
  terraform_directory:
    description: Directory holding Terraform code to analyze
    default: .
  terrafetch_version:
    description: Terrafetch version (e.g. 0.2.0 or "latest")
    default: latest

outputs:
  terrafetch-return-code:
    description: Exit code from the terrafetch run
    value: ${{ steps.terrafetch.outputs.terrafetch-return-code }}

runs:
  using: composite
  steps:
    - id: terrafetch
      run: $GITHUB_ACTION_PATH/action.sh
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_OUTPUT_FILE: ${{ inputs.output_file }}
        INPUT_TERRAFORM_DIRECTORY: ${{ inputs.terraform_directory }}
        INPUT_TERRAFETCH_VERSION: ${{ inputs.terrafetch_version }}
